# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('host', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('fee', models.IntegerField(default=0)),
                ('rules', models.TextField(blank=True, null=True)),
                ('prerequistes', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
