# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-16 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171117_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField()),
                ('star', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(3, 5, 21, 651681)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(3, 5, 21, 651681)),
        ),
    ]
