# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-23 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171121_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codechef_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='codechef_ques',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 45, 10, 322472)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 45, 10, 322472)),
        ),
    ]
