# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-09 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(22, 49, 10, 252632)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(22, 49, 10, 252632)),
        ),
    ]
