# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171113_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Fullname',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='registration',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='query',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 1, 11, 146675)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 1, 11, 145670)),
        ),
    ]
